# Generated by Django 2.0.5 on 2018-06-18 10:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Agent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100)),
                ('date', models.DateField(auto_now_add=True)),
                ('heure', models.TimeField(blank=True, null=True)),
                ('nom_etablissement', models.CharField(max_length=400)),
                ('type_etablissement', models.CharField(max_length=400)),
                ('adresse', models.CharField(max_length=500)),
                ('type_compte', models.CharField(choices=[('EPARGNE', 'Epargne'), ('COURANT', 'Courant')], max_length=8)),
                ('type_client', models.CharField(choices=[('INDIVIDU', 'Individu'), ('AGENT', 'Agent'), ('MARCHANT', 'Marchant')], max_length=8)),
                ('nom_client', models.CharField(max_length=200)),
                ('sexe', models.CharField(choices=[('MAXCULIN', 'Masculin'), ('FEMININ', 'Feminin')], max_length=8)),
                ('depot', models.CharField(max_length=30)),
            ],
        ),
    ]
