# Generated by Django 2.0.5 on 2018-06-18 13:06

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('eco_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='agent',
            name='email',
            field=models.EmailField(default=django.utils.timezone.now, max_length=254),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='agent',
            name='numero',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
