# Generated by Django 2.0.5 on 2018-06-18 13:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eco_app', '0002_auto_20180618_1406'),
    ]

    operations = [
        migrations.AlterField(
            model_name='agent',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AlterField(
            model_name='agent',
            name='heure',
            field=models.TimeField(),
        ),
    ]
